name: "Bug Report"
description: "Report a problem or unexpected behavior in SmartLinker."
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug! Please fill out the information below.**
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Screenshots or Logs"
      description: "Add screenshots, logs, or error messages if available."
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Provide details about your environment (OS, Unity version, etc.)"
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Anything else we should know?"