name: "Feature Request"
description: "Propose a new feature or enhancement for SmartLinker."
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Suggest a new feature or improvement!**
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Describe the new feature or enhancement."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: "Use Case / Motivation"
      description: "Explain the problem and how this feature would help."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Possible Alternatives"
      description: "Have you considered any alternative solutions?"
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Anything else we should know?"